name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command

      - name: Compile
        run: |
          yarn compile
        env:
          MAINNET_API_KEY: ${{ secrets.MAINNET_API_KEY }}
          GOERLI_API_KEY: ${{ secrets.GOERLI_API_KEY }}
          OPTIMISM_API_KEY: ${{ secrets.OPTIMISM_API_KEY }}
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          ARBITRUM_API_KEY: ${{ secrets.ARBITRUM_API_KEY }}
